import Link from "next/link";
import { brand } from "@/lib/brand";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="mt-3 space-y-3">{children}</div>
    </section>
  );
}

export function PrivacyPolicyContent() {
  return (
    <>
      <p>
        This Privacy Policy explains how {brand.name} (&quot;{brand.name}&quot;,
        &quot;we&quot;, &quot;us&quot;) collects, uses, stores, and shares
        information when you use {brand.domain} and related services (the
        &quot;Service&quot;). By using the Service, you agree to this Policy.
      </p>

      <Section title="1. Who we are">
        <p>
          {brand.name} operates an AI-powered website builder for local
          businesses at{" "}
          <a
            href={`https://${brand.domain}`}
            className="text-brand-light underline-offset-2 hover:underline"
          >
            {brand.domain}
          </a>
          . For privacy questions or requests, contact us at{" "}
          <a
            href={`mailto:${brand.supportEmail}`}
            className="text-brand-light underline-offset-2 hover:underline"
          >
            {brand.supportEmail}
          </a>
          .
        </p>
      </Section>

      <Section title="2. Information we collect">
        <p>We collect information you provide and data generated by your use of the Service:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong className="text-foreground">Account data</strong> — email
            address and, if you use Google sign-in, basic profile information
            from your Google account (such as name and email).
          </li>
          <li>
            <strong className="text-foreground">Business data</strong> — business
            name, category, location, description, services, phone number, and
            contact email you enter to generate or edit a website.
          </li>
          <li>
            <strong className="text-foreground">Generated content</strong> — AI
            drafts, previews, published sites, edits, and project metadata stored
            in your account.
          </li>
          <li>
            <strong className="text-foreground">Early access / leads</strong> —
            email and optional business name when you request access or join a
            waitlist.
          </li>
          <li>
            <strong className="text-foreground">Billing data</strong> — plan
            selection and payment-related records (for example crypto checkout
            order references). We do not store full payment card numbers on our
            servers.
          </li>
          <li>
            <strong className="text-foreground">Usage and analytics</strong> —
            pages visited, device/browser type, approximate location derived from
            IP, referral source, and interactions with the Service (including
            optional Google Analytics and Meta Pixel, if enabled).
          </li>
          <li>
            <strong className="text-foreground">Technical logs</strong> — IP
            address, timestamps, error logs, and security events needed to
            operate and protect the Service.
          </li>
        </ul>
      </Section>

      <Section title="3. How we use AI">
        <p>
          {brand.name} uses artificial intelligence to generate and improve
          website content, layouts, SEO text, and related assets. When you
          generate or improve a site, we send relevant business information you
          provide (such as business name, location, services, and description)
          to AI providers — currently <strong className="text-foreground">OpenAI</strong> —
          to produce outputs.
        </p>
        <p>
          Do not submit sensitive personal data you are not comfortable sharing
          with AI processors (for example health information, government IDs, or
          financial account numbers). You are responsible for ensuring you have
          the right to provide business information you enter.
        </p>
      </Section>

      <Section title="4. How we use your information">
        <p>We use collected information to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>create, preview, edit, publish, and host websites you request;</li>
          <li>authenticate you and manage your account and projects;</li>
          <li>process subscriptions and billing;</li>
          <li>improve quality, reliability, and safety of AI outputs;</li>
          <li>provide support and respond to requests;</li>
          <li>send service-related messages (not marketing spam without consent);</li>
          <li>monitor usage, prevent abuse, and secure the platform;</li>
          <li>comply with legal obligations.</li>
        </ul>
      </Section>

      <Section title="5. Legal bases (EEA / UK users)">
        <p>If you are in the European Economic Area or United Kingdom, we process personal data on these bases:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong className="text-foreground">Contract</strong> — to provide
            the Service you signed up for.
          </li>
          <li>
            <strong className="text-foreground">Legitimate interests</strong> —
            to improve the Service, prevent fraud, and keep the platform secure
            (balanced against your rights).
          </li>
          <li>
            <strong className="text-foreground">Consent</strong> — where
            required for optional analytics/marketing cookies or waitlist
            communications.
          </li>
          <li>
            <strong className="text-foreground">Legal obligation</strong> — where
            law requires retention or disclosure.
          </li>
        </ul>
      </Section>

      <Section title="6. How we share information">
        <p>We do not sell your personal information. We share data only with:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong className="text-foreground">Service providers</strong> who
            help us operate the platform, such as hosting (Vercel), database
            (Supabase), authentication (Google), email delivery, analytics, and
            AI inference (OpenAI).
          </li>
          <li>
            <strong className="text-foreground">Published websites</strong> —
            contact details you choose to publish (phone, email, address) are
            visible to visitors of your live site.
          </li>
          <li>
            <strong className="text-foreground">Legal and safety</strong> — when
            required by law or to protect rights, safety, and integrity of users
            and the Service.
          </li>
          <li>
            <strong className="text-foreground">Business transfers</strong> — in
            connection with a merger, acquisition, or asset sale, with notice where
            required.
          </li>
        </ul>
      </Section>

      <Section title="7. International transfers">
        <p>
          We and our providers may process data in the United States and other
          countries. Where required, we rely on appropriate safeguards (such as
          Standard Contractual Clauses) for cross-border transfers.
        </p>
      </Section>

      <Section title="8. Retention">
        <p>
          We keep account and project data while your account is active and for a
          reasonable period afterward so you can restore work or resolve billing
          issues. Logs and analytics may be kept for shorter operational periods.
          You may delete projects or request account deletion by contacting{" "}
          {brand.supportEmail}. We may retain limited data where law or legitimate
          business needs require it (for example billing records).
        </p>
      </Section>

      <Section title="9. Security">
        <p>
          We use administrative, technical, and organizational measures to protect
          your information (encryption in transit, access controls, and secure
          hosting). No method of transmission or storage is 100% secure; please
          use a strong, unique login method and protect your account credentials.
        </p>
      </Section>

      <Section title="10. Your rights">
        <p>
          Depending on where you live, you may have rights to access, correct,
          delete, restrict, or port your personal data, and to object to certain
          processing. You may also withdraw consent where processing is
          consent-based, and lodge a complaint with your local data protection
          authority.
        </p>
        <p>
          To exercise these rights, email{" "}
          <a
            href={`mailto:${brand.supportEmail}`}
            className="text-brand-light underline-offset-2 hover:underline"
          >
            {brand.supportEmail}
          </a>
          . We may need to verify your identity before fulfilling a request.
        </p>
      </Section>

      <Section title="11. Cookies and analytics">
        <p>
          We use essential cookies for authentication and session management.
          With your consent where required, we may use analytics tools (such as
          Google Analytics or Meta Pixel) to understand how the Service is used.
          You can control cookies through your browser settings and, where
          available, our cookie preferences.
        </p>
      </Section>

      <Section title="12. Children">
        <p>
          The Service is intended for businesses and users aged 18 and older. We
          do not knowingly collect personal information from children under 16
          (or the applicable age in your jurisdiction). Contact us if you believe
          a child has provided data and we will delete it.
        </p>
      </Section>

      <Section title="13. Changes to this Policy">
        <p>
          We may update this Privacy Policy from time to time. We will post the
          revised version on this page and update the &quot;Last updated&quot;
          date. Material changes may be communicated by email or in-product notice
          where appropriate.
        </p>
      </Section>

      <Section title="14. Contact">
        <p>
          Questions about this Policy or our data practices:{" "}
          <a
            href={`mailto:${brand.supportEmail}`}
            className="text-brand-light underline-offset-2 hover:underline"
          >
            {brand.supportEmail}
          </a>
          . Website:{" "}
          <Link href="/" className="text-brand-light underline-offset-2 hover:underline">
            {brand.domain}
          </Link>
          .
        </p>
      </Section>
    </>
  );
}
